### ISSUE TITLE
Volume issue in MiSTer cores

### ISSUE THREAD

**Issue by mills32** [jotego/jtopl#11]
Hi, Thanks a lot for this great opl implementation :).

I noticed some opl/opl2 tunes from a lot of games do not sound as the original ones.

For example the music from terra cresta:
1 - Recorded from MiSTer core): [Terra cresta_JTOPL.zip](https://github.com/jotego/jtopl/files/9485455/Terra.cresta_JTOPL.zip)
2 - Original (vgmrips.net) click on "02 theme of terracresta": https://vgmrips.net/packs/pack/terra-cresta

I noticed the drums have very low volume on jtopl.

This opl implementation has been included in the pcxt core, so I made a vgm player for 8088 cpu, and the result is the same. I found a lot of themes with low volume drums, all of them seem to use the "percussion mode" of ym3526 (terra cresta) and also ym3812. 

In percussion mode, the chip can output 6 melodic instruments and 5 percussion ones (which seem to output wrong, or at very low volume in the cores).

Another example is the Wacky Wheels intro theme (ym3812):
1 - Recorded from PCXT core, sorry this also has some clicks and noises, I don't know if this is a problem of the core, or the opl: [WWHeels_JTOPL.zip](https://github.com/jotego/jtopl/files/9485475/WWHeels_JTOPL.zip)
2 - Original (vgmrips.net) click on "02 Dream": https://vgmrips.net/packs/pack/wacky-wheels-ibm-pc-at

Thanks!.

**Comment by ghost** [comment]
There are other cores that have reported issues with audio that uses jtopl:

Toaplan V1:
[Issue here](https://github.com/va7deo/zerowing#:~:text=Audio%20issues%20known%2C%20may%20be%20an%20issue%20with%20the%20jtopl2%20core%20or%20the%20current%20usage%0A(No%20need%20to%20report%20further%20audio%20issues))


ArmedF Nitchibutsu:
[Issue here](https://github.com/va7deo/ArmedF#:~:text=Audio%20issues%20known%2C%20may%20be%20an%20issue%20with%20the%20jtopl2%20core%20or%20the%20current%20usage%0A(No%20need%20to%20report%20further%20audio%20issues))

Prehistoric Isle In 1930:
 [Issue here](https://github.com/va7deo/PrehistoricIsle#:~:text=Audio%20issues%20known%2C%20may%20be%20an%20issue%20with%20the%20jtopl2%20core%20or%20the%20current%20usage%0A(No%20need%20to%20report%20further%20audio%20issues%3B%20appears%20there%20are%20no%20audio%20issues%20in%20this%20core)%20%5BIssue%5D)

**Comment by ghost** [comment]
Another core that highlights this issue:
[SNK68](https://github.com/va7deo/SNK68#:~:text=Audio%20issues%20known%2C%20may%20be%20an%20issue%20with%20the%20jtopl2%20core%20or%20the%20current%20usage%0A(No%20need%20to%20report%20further%20audio%20issues%3B%20appears%20there%20are%20no%20audio%20issues%20in%20this%20core)%20%5BIssue%5D)

**Comment by jotego** [comment]
Thanks for the detailed report.
The volume for percussion operators should have been 2x. That is fixed in commit a217a0c.

**Comment by sherhacky** [comment]
@jotego At least for the Toaplan core, https://github.com/jotego/jtopl/commit/a217a0c45c772967f8330247d52fe4dbba5fbb58 appears to have only partially addressed the issue; [here is a report with examples on that issue in Truxton](https://github.com/va7deo/zerowing/issues/43#issuecomment-2041294467), where it sounds like some of the restored instruments are too loud.

For reference [here is the Stg 1 BGM from Outzone](https://youtu.be/Z0AWtigWeYE) in the build with the fix in place; some percussion is still missing, and other instruments sound blown out/distorted compared to [PCB](https://drive.google.com/file/d/1iQcNg3I362-YyhUKCtfUQ1FB1lqp7hVo/view?usp=sharing).

**Comment by Toryalai1** [comment]
> @jotego At least for the Toaplan core, [a217a0c](https://github.com/jotego/jtopl/commit/a217a0c45c772967f8330247d52fe4dbba5fbb58) appears to have only partially addressed the issue; [here is a report with examples on that issue in Truxton](https://github.com/va7deo/zerowing/issues/43#issuecomment-2041294467), where it sounds like some of the restored instruments are too loud.
> 
> For reference [here is the Stg 1 BGM from Outzone](https://youtu.be/Z0AWtigWeYE) in the build with the fix in place; some percussion is still missing, and other instruments sound blown out/distorted compared to [PCB](https://drive.google.com/file/d/1iQcNg3I362-YyhUKCtfUQ1FB1lqp7hVo/view?usp=sharing).

<del>@sherhacky it is better if you open a new ticket here and reference this ticket </del>

**Comment by atrac17** [comment]
@Toryalai1  but it's still the same issue. Why can't it can be reopened.

**Comment by Toryalai1** [comment]
You are correct. I’ll edit my comment. Thanks
